/************************************************************************************************
** File created by QxEntityEditor 1.2.5 (2020/07/07 22:14) : please, do NOT modify this file ! **
************************************************************************************************/

#ifndef _LICENTA_EXPORT_H_
#define _LICENTA_EXPORT_H_

#ifdef _MSC_VER
#pragma once
#endif

#ifdef _BUILDING_LICENTA
#define LICENTA_EXPORT QX_DLL_EXPORT_HELPER
#else // _BUILDING_LICENTA
#define LICENTA_EXPORT QX_DLL_IMPORT_HELPER
#endif // _BUILDING_LICENTA

#ifdef _BUILDING_LICENTA
#define QX_REGISTER_HPP_LICENTA QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_LICENTA QX_REGISTER_CPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_LICENTA QX_REGISTER_COMPLEX_CLASS_NAME_HPP_EXPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_LICENTA QX_REGISTER_COMPLEX_CLASS_NAME_CPP_EXPORT_DLL
#else // _BUILDING_LICENTA
#define QX_REGISTER_HPP_LICENTA QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_LICENTA QX_REGISTER_CPP_IMPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_HPP_LICENTA QX_REGISTER_COMPLEX_CLASS_NAME_HPP_IMPORT_DLL
#define QX_REGISTER_COMPLEX_CLASS_NAME_CPP_LICENTA QX_REGISTER_COMPLEX_CLASS_NAME_CPP_IMPORT_DLL
#endif // _BUILDING_LICENTA

#ifndef QX_DLL_EXPORT_LICENTA_SINGLETON_HPP
#ifdef _BUILDING_LICENTA
#define QX_DLL_EXPORT_LICENTA_SINGLETON_HPP(x) /* Nothing */
#else // _BUILDING_LICENTA
#define QX_DLL_EXPORT_LICENTA_SINGLETON_HPP(x) QX_DLL_EXPORT_TEMPLATE_HPP(class, qx::QxSingleton< x >)
#endif // _BUILDING_LICENTA
#endif // QX_DLL_EXPORT_LICENTA_SINGLETON_HPP

#ifndef QX_DLL_EXPORT_LICENTA_SINGLETON_CPP
#ifdef _BUILDING_LICENTA
#define QX_DLL_EXPORT_LICENTA_SINGLETON_CPP(x) QX_DLL_EXPORT_TEMPLATE_CPP(class, qx::QxSingleton< x >)
#else // _BUILDING_LICENTA
#define QX_DLL_EXPORT_LICENTA_SINGLETON_CPP(x) /* Nothing */
#endif // _BUILDING_LICENTA
#endif // QX_DLL_EXPORT_LICENTA_SINGLETON_CPP

#endif // _LICENTA_EXPORT_H_
